### ISSUE TITLE
line 57 SyntaxError

### ISSUE THREAD

**Issue by leungzw** [freelamb/simple_http_server#4]
File "simple_http_server.py", line 57
    print r, info, "by: ", self.client_address
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(r, info, "by: ", self.client_address)?

**Comment by freelamb** [comment]
python version is 2.x or 3.x?

**Comment by leungzw** [comment]
# python -V
Python 3.6.8

**Comment by kungfuboy** [comment]
Me too.  Python 3.9.4

![image](https://user-images.githubusercontent.com/10394818/116024204-48108900-a680-11eb-9a08-cf7eb84a4a54.png)

**Comment by freelamb** [comment]
now, support python 3.x

thank you for issuing

**Comment by freelamb** [comment]
> # python -V
> Python 3.6.8



> File "simple_http_server.py", line 57
> print r, info, "by: ", self.client_address
> ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(r, info, "by: ", self.client_address)?

I have solved the problem.
